#ifndef RAPPAS_CPP_PHYML_H
#define RAPPAS_CPP_PHYML_H

#include <string>
#include <unordered_map>

class proba_matrix;


/// Load a posterior probability matrix from a file, generated by PhyML
proba_matrix load_phyml_probas(const std::string& file_name);

//--------------------------------------------------------------------------------------------------------------------
/// \brief A node mapper for a phylogenetic tree.
/// \details Ancestral reconstruction programs (such as PhyML) in the output can refer
/// nodes of an input phylogenetic tree with their own name convention. This class is
/// used to store this name convention (both directions).
struct node_mapping
{
    using map_t = std::unordered_map<std::string, std::string>;

    map_t to_phyml;
    map_t from_phyml;
};

/// Load a node mapping from file
node_mapping load_node_mapping(const std::string& file_name);

#endif