#ifndef RAPPAS_CPP_PHYML_H
#define RAPPAS_CPP_PHYML_H

#include <string>
#include <unordered_map>
#include "row.h"

class proba_matrix;

/// Load a posterior probability matrix from a file, generated by PhyML
proba_matrix load_phyml_probas(const std::string& file_name);

using artree_label_mapping = std::unordered_map<std::string, branch_id>;
using extended_mapping = std::unordered_map<std::string, branch_id>;

/// Load a node mapping from file
extended_mapping load_extended_mapping(const std::string& file_name);
artree_label_mapping load_artree_mapping(const std::string& file_name);


#endif