name: build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-epik:
    name: ${{matrix.buildname}}

    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04, macos-13, macos-12 ]
        include:
          - os: ubuntu-22.04
            buildname: 'ubuntu-22.04'
            triplet: x64-linux
            compiler: gcc_64
          - os: ubuntu-20.04
            buildname: 'ubuntu-20.04'
            triplet: x64-linux
            compiler: gcc_64
          - os: macos-13
            buildname: 'macos-13'
            triplet: x64-osx
            compiler: clang_64
          - os: macos-12
            buildname: 'macos-12'
            triplet: x64-osx
            compiler: clang_64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: (MacOS) Install dependencies
        if: runner.os == 'macOS'
        run: brew install boost libomp

      - name: (Linux) Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -yq build-essential cmake libboost-dev libboost-serialization-dev libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev zlib1g-dev rapidjson-dev libquadmath0 python3-pip && pip install click

      - name: Configure CMake
        run: cmake -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{runner.workspace}}/bin --config $BUILD_TYPE

      - name: Test build successful
        working-directory: ${{runner.workspace}}/bin
        shell: bash
        run: test -f ${{runner.workspace}}/bin/epik/epik-dna && test -f ${{runner.workspace}}/bin/epik/epik-dna

      - name: Test python script
        working-directory: ${{runner.workspace}}/bin
        shell: bash
        run: ./epik.py place --help
